version: 3.1.4.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  include_nuget_references: true
environment:
    COVERALLS_REPO_TOKEN:  
       secure: JC9AZf9AdKHmaWmaWMq/fnFaGCIkVvdQjIfHOuWGTXycseJYYbBk+Q7HUbxHJryU
after_test: 
  - Source\packages\OpenCover.4.5.3723\OpenCover.Console.exe -mergeoutput -register:user -target:"Source\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:""Source\Mirabeau.MsSql.Library.UnitTests\bin\Release\Mirabeau.MsSql.Library.UnitTests.dll"" /noshadow" -output:opencoverCoverage.xml
  - Source\packages\OpenCover.4.5.3723\OpenCover.Console.exe -mergeoutput -register:user -target:"Source\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:""Source\Mirabeau.MySql.Library.UnitTests\bin\Release\Mirabeau.MySql.Library.UnitTests.dll"" /noshadow" -output:opencoverCoverage.xml
  - Source\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken %COVERALLS_REPO_TOKEN% --commitBranch %APPVEYOR_REPO_BRANCH%
deploy:
- provider: NuGet
  api_key:
    secure: sgFlZQ6SSawwtiKcN23uO3hdwEGvy8M4hA8ye2iTAPdmz4gByofx2ZljpJHZ+Pm3
  on:
    branch: master